# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config.yaml"
report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

# rules for updating genetic map and generating MareyMap inputs
rule convert_map:
    input:
        "data/{basename}_coords.tsv"
    output:
        "data/{basename}_coords.new.tsv"

include: "rules/other.smk"
